#
##这是hibernate
##这里是项目的配置文件
## 设置项目运行的端口：
#
#server.port=8080
#
## 这里是数据库连接驱动的设置，设置了一些连接参数来使连接有效。
## 数据库的连接驱动
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 连接数据库的地址，注意，我这里数据库的端口是3308，我自己配置的，默认情况下是3306端口，请根据自己的情况修改
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/alice?serverTimezone=UTC&useSSL=false
## 连接的账号和密码，也要根据自己情况去修改。
#spring.datasource.username=root
#spring.datasource.password=123456
#
## 这里配置的是hibernate 框架的信息，数据库的访问使用了 hibernate 框架。
## 这里是数据库的连接类型信息，选择的是mysql 数据库。
#spring.jpa.database=mysql
## 这里的参数有五种，常用的就是 create 和 update ，区别在于create 在每一次启动应用的时候都会重新创建数据库，并把之前的数据全部删掉，而update 则是采用增量的方式来进行创建，只更新修改的了部分，保留未修改部分的数据
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/alice?serverTimezone=UTC&useSSL=false
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
   #password: null 还没有password
    database: 0  #配置redis的0~15编号
    timeout: 1000s # 数据库连接超时时间,2.0 中该参数的类型为Duration,这里在配置
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大连接活跃数，负数为不限制
        max-active: -1
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.model
